requests:
#  - http://localhost:8000/timeout
#  - http://localhost:8000/
#  - http://localhost:8000/404
 - method: 'POST'
   url: http://localhost:8000/post
   data: "holaaaa"
   headers:
     content-type: text/plain
 - method: 'POST'
   url: http://localhost:8000/post
   data:
     hola: mundo
     a: 1
   headers:
     content-type: application/json

run_every: 60000
log_level: debug
request_timeout: 5000
smtp:
  host: ${{ SMTP_HOST  }}
  port: ${{ SMTP_PORT  }}
  username: ${{ SMTP_USERNAME  }}
  from: ${{ SMTP_FROM  }}
  to: ${{ SMTP_TO  }}
  password: ${{ SMTP_PASSWORD  }}
