requests:
#  - http://jupegarnica.com

#  Or the same using a request schema
#  - method: GET
#    url: http://jupegarnica.com


#  - method: POST
#    url: http://localhost:8000/post
#    data: hello
#    headers:
#      content-type: text/plain

#  - method: PATCH
#    headers:
#      content-type: application/json
#    url: http://localhost:8000/post
#    data:
#      title: hello
#      body: lorem ipsum

run_every: 60000
log_level: ${{ LOG_LEVEL  }} # DEBUG, INFO, WARNING, ERROR, CRITICAL
request_timeout: 10000
smtp:
  host: ${{ SMTP_HOST  }}
  port: ${{ SMTP_PORT  }}
  username: ${{ SMTP_USERNAME  }}
  from: ${{ SMTP_FROM  }}
  to: ${{ SMTP_TO  }}
  password: ${{ SMTP_PASSWORD  }}
