requests:
 - https://jupegarnica.com
 - https://juanchorro.com
 - http://valencia.io
 - https://datsme.life

#  - http://shop.datsme.life:444




run_every: 60000
log_level: ${{ LOG_LEVEL  }}
logs_dir: 'logs'
request_timeout: 10000
smtp:
  host: ${{ SMTP_HOST  }}
  port: ${{ SMTP_PORT  }}
  username: ${{ SMTP_USERNAME  }}
  from: ${{ SMTP_FROM  }}
  to: ${{ SMTP_TO  }}
  password: ${{ SMTP_PASSWORD  }}
