log_level: $
run_every: 30000
request_timeout: 10000
requests:
  - http://jupegarnica.com/random
  # - http://jupegarnica.com/404
smtp:
  host: '${{SMTP_HOST}}'
  username: '${{SMTP_USERNAME}}'
  password: '${{SMTP_PASSWORD}}'
  port: '${{SMTP_PORT}}'
  from: '${{SMTP_FROM}}'
  to: '${{SMTP_TO}}'
