
# For more information see: https://github.com/denolib/setup-deno

name: Cron monitor

on:
  workflow_dispatch:
  schedule:
  # - cron: "* * * * *"
  - cron: "*/10 * * * *"

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_FROM: ${{ secrets.SMTP_FROM }}
      SMTP_TO: ${{ secrets.SMTP_TO }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: v1.5.4

      - name: Run monitoring
        run: deno run -A monitoring-once.ts
      - name: push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'new log'
          force-add: 'false'
          files: logs/*
          name:  monitor
          email: jupegarnica@gmail.com
